#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# Ensure that all Rust code is well-formatted
cargo fmt --check --quiet
if [ $? != 0 ]
then
	cat <<\EOF
Error: cargo fmt check failed.

Run "cargo fmt" to properly format your code before committing.
EOF
	exit 1
fi

# Ensure there are no error-level lint violations or compile errors
# Redirect output to /dev/null because there's no way to shut clippy up
# and the redirect keeps any git errors clean
cargo clippy >/dev/null 2>/dev/null
if [ $? != 0 ]
then
	cat <<\EOF
Error: Clippy lint check failed.

Fix any errors before committing. "cargo clippy --fix" can automatically apply
many lint suggestions.
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
